### PR TITLE
Prevent throw during `--single` mode

### LINKED ISSUE #73: --single breaks now.
It seems like it's throwing when the directory doesn't exist:

```js
if (await pathType.dir(related)) { // ...
```

This used to work, but now it's broken :(

I'm simply using `serve ./build --single` and a `react-app` created app.

### PR DESCRIPTION
**Pull request by lukeed**
The `path-type` module does not wrap its `dir()` functions with any kind of `catch` handler, so it requires that all strings must be pre-verified. 

During `--single` mode, any nested route (eg, `/blog/article2`) is eventually passed along as `/Users/.../dist/blog/article2`, which does not exist (assuming `dist` is the base directory).

And so, because non-existent paths are sent to `pathType.dir()`, a `Error: ENOENT` is thrown, which causes the 502 error that I & others were experiencing. 

Closes #73

### CODE REVIEW

File: lib/server.js [hunk 1]
```diff
@@ -43,19 +43,21 @@ module.exports = async (req, res, flags, current, ignoredFiles) => {
 
   related = decodeURIComponent(path.format(related))
 
+  const relatedExists = fs.existsSync(related)
```
Comment (leo) [inline lib/server.js]: Can you do `await fs.exists()` please? Not sure if that will throw or not. Wrap it in `try` if it will... 😊

Comment (lukeed) [inline lib/server.js]: Unfortunately `fs.exists` is deprecated. Should I use a module instead?

Comment (leo) [inline lib/server.js]: @lukeed Ahhhh, you're right. Nope!

**Comment by lukeed** [comment]
Thanks!
